// Smirel 订阅套餐静态配置（与 backend/migrations/195_smiral_plans_seed.sql 保持同步）
// 后端对接就绪后，可改为从 /api/v1/subscription-plans 拉取

export type ProductLine = 'gpt_plus' | 'gpt_pro' | 'claude_no_fable' | 'claude_fable' | 'domestic'
export type PlanTier = 'light' | 'pro' | 'enterprise_trial'

export interface SmiralPlan {
  id: string
  productLine: ProductLine
  tier: PlanTier
  groupName: string
  name: string
  priceCNY: number
  monthlyUSDQuota: number
  weeklyUSDQuota?: number
  paygPricePerUSD: number
  effectivePricePerUSD: number
  costMultiplier: number
  supportModels: string
  benefits: string[]
  isEnterprise: boolean
  seats: number
  concurrency: number
  whitelistOnly: boolean
  circuitBreakerEnabled: boolean
}

export const SMIRAL_PLANS: SmiralPlan[] = [
  // GPT 线路 3 档
  {
    id: 'gpt-plus-light',
    productLine: 'gpt_plus',
    tier: 'light',
    groupName: 'Muxway · GPT Plus',
    name: 'GPT Plus 轻享月卡',
    priceCNY: 89,
    monthlyUSDQuota: 190,
    weeklyUSDQuota: 76,
    paygPricePerUSD: 0.50,
    effectivePricePerUSD: 0.47,
    costMultiplier: 0.10,
    supportModels: 'GPT-6 Astra / GPT-5.6 Sol / GPT-5.6 Terra / GPT-5.6 Luna',
    benefits: ['1 席', '5 并发', '无日限额', '周/月额度控制'],
    isEnterprise: false,
    seats: 1,
    concurrency: 5,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'gpt-pro-pro',
    productLine: 'gpt_pro',
    tier: 'pro',
    groupName: 'Muxway · GPT Pro',
    name: 'GPT Pro 专业月卡',
    priceCNY: 379,
    monthlyUSDQuota: 600,
    weeklyUSDQuota: 240,
    paygPricePerUSD: 0.75,
    effectivePricePerUSD: 0.63,
    costMultiplier: 0.20,
    supportModels: 'GPT-6 Astra / GPT-5.6 Sol / GPT-5.6 Terra / GPT-5.6 Luna',
    benefits: ['1 席', '5 并发', '无日限额', '周/月额度控制'],
    isEnterprise: false,
    seats: 1,
    concurrency: 5,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'gpt-pro-enterprise',
    productLine: 'gpt_pro',
    tier: 'enterprise_trial',
    groupName: 'Muxway · GPT Pro',
    name: 'GPT Pro 企业试运行',
    priceCNY: 2469,
    monthlyUSDQuota: 3000,
    paygPricePerUSD: 0.75,
    effectivePricePerUSD: 0.82,
    costMultiplier: 0.20,
    supportModels: 'GPT-6 Astra / GPT-5.6 Sol / GPT-5.6 Terra / GPT-5.6 Luna',
    benefits: ['20 席', '30+ 并发', '独享 quota', '无日限额', '白名单销售'],
    isEnterprise: true,
    seats: 20,
    concurrency: 30,
    whitelistOnly: true,
    circuitBreakerEnabled: false,
  },

  // Claude 无 Fable 3 档
  {
    id: 'claude-no-fable-light',
    productLine: 'claude_no_fable',
    tier: 'light',
    groupName: 'Muxway · ClaudeCode',
    name: 'ClaudeCode Plus 轻享月卡',
    priceCNY: 559,
    monthlyUSDQuota: 850,
    weeklyUSDQuota: 340,
    paygPricePerUSD: 0.70,
    effectivePricePerUSD: 0.66,
    costMultiplier: 0.30,
    supportModels: 'Claude Opus 5 / Sonnet 5 / Haiku 4.5（不含 Fable 5.1）',
    benefits: ['1 席', '8 并发', '无日限额'],
    isEnterprise: false,
    seats: 1,
    concurrency: 8,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'claude-no-fable-pro',
    productLine: 'claude_no_fable',
    tier: 'pro',
    groupName: 'Muxway · ClaudeCode',
    name: 'ClaudeCode Plus 标准月卡',
    priceCNY: 889,
    monthlyUSDQuota: 1500,
    weeklyUSDQuota: 600,
    paygPricePerUSD: 0.70,
    effectivePricePerUSD: 0.59,
    costMultiplier: 0.30,
    supportModels: 'Claude Opus 5 / Sonnet 5 / Haiku 4.5（不含 Fable 5.1）',
    benefits: ['1 席', '12 并发', '无日限额'],
    isEnterprise: false,
    seats: 1,
    concurrency: 12,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'claude-no-fable-enterprise',
    productLine: 'claude_no_fable',
    tier: 'enterprise_trial',
    groupName: 'Muxway · ClaudeCode',
    name: 'ClaudeCode Plus 企业试运行',
    priceCNY: 2309,
    monthlyUSDQuota: 3000,
    paygPricePerUSD: 0.70,
    effectivePricePerUSD: 0.77,
    costMultiplier: 0.30,
    supportModels: 'Claude Opus 5 / Sonnet 5 / Haiku 4.5（不含 Fable 5.1）',
    benefits: ['20 席', '30+ 并发', '独享 quota', '白名单销售'],
    isEnterprise: true,
    seats: 20,
    concurrency: 30,
    whitelistOnly: true,
    circuitBreakerEnabled: false,
  },

  // Claude 含 Fable / Max 3 档
  {
    id: 'claude-fable-light',
    productLine: 'claude_fable',
    tier: 'light',
    groupName: 'Muxway · ClaudeCode Max',
    name: 'ClaudeCode Max 轻享月卡',
    priceCNY: 1179,
    monthlyUSDQuota: 540,
    weeklyUSDQuota: 216,
    paygPricePerUSD: 2.30,
    effectivePricePerUSD: 2.18,
    costMultiplier: 1.20,
    supportModels: 'Claude Fable 5.1 / Opus 5 / Sonnet 5 / Haiku 4.5',
    benefits: ['1 席', '5 并发', '限量开放', '白名单优先'],
    isEnterprise: false,
    seats: 1,
    concurrency: 5,
    whitelistOnly: true,
    circuitBreakerEnabled: true,
  },
  {
    id: 'claude-fable-pro',
    productLine: 'claude_fable',
    tier: 'pro',
    groupName: 'Muxway · ClaudeCode Max',
    name: 'ClaudeCode Max 标准月卡',
    priceCNY: 2049,
    monthlyUSDQuota: 1050,
    weeklyUSDQuota: 420,
    paygPricePerUSD: 2.30,
    effectivePricePerUSD: 1.95,
    costMultiplier: 1.20,
    supportModels: 'Claude Fable 5.1 / Opus 5 / Sonnet 5 / Haiku 4.5',
    benefits: ['1 席', '8 并发', '限量开放'],
    isEnterprise: false,
    seats: 1,
    concurrency: 8,
    whitelistOnly: true,
    circuitBreakerEnabled: true,
  },
  {
    id: 'claude-fable-enterprise',
    productLine: 'claude_fable',
    tier: 'enterprise_trial',
    groupName: 'Muxway · ClaudeCode Max',
    name: 'ClaudeCode Max 企业试运行',
    priceCNY: 9099,
    monthlyUSDQuota: 3600,
    paygPricePerUSD: 2.30,
    effectivePricePerUSD: 2.53,
    costMultiplier: 1.20,
    supportModels: 'Claude Fable 5.1 / Opus 5 / Sonnet 5 / Haiku 4.5',
    benefits: ['20 席', '30+ 并发', '白名单开放', 'Fable 溢价'],
    isEnterprise: true,
    seats: 20,
    concurrency: 30,
    whitelistOnly: true,
    circuitBreakerEnabled: true,
  },

  // 国产模型 3 档
  {
    id: 'domestic-light',
    productLine: 'domestic',
    tier: 'light',
    groupName: 'Muxway · 国产模型',
    name: '国产模型轻享月卡',
    priceCNY: 69,
    monthlyUSDQuota: 160,
    weeklyUSDQuota: 64,
    paygPricePerUSD: 0.50,
    effectivePricePerUSD: 0.43,
    costMultiplier: 0.10,
    supportModels: 'DeepSeek / Kimi / GLM / Qwen 等系统实时上架模型',
    benefits: ['1 席', '5 并发', '无日限额'],
    isEnterprise: false,
    seats: 1,
    concurrency: 5,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'domestic-pro',
    productLine: 'domestic',
    tier: 'pro',
    groupName: 'Muxway · 国产模型',
    name: '国产模型专业月卡',
    priceCNY: 209,
    monthlyUSDQuota: 500,
    weeklyUSDQuota: 200,
    paygPricePerUSD: 0.50,
    effectivePricePerUSD: 0.42,
    costMultiplier: 0.10,
    supportModels: 'DeepSeek / Kimi / GLM / Qwen 等系统实时上架模型',
    benefits: ['1 席', '10 并发', '无日限额'],
    isEnterprise: false,
    seats: 1,
    concurrency: 10,
    whitelistOnly: false,
    circuitBreakerEnabled: false,
  },
  {
    id: 'domestic-enterprise',
    productLine: 'domestic',
    tier: 'enterprise_trial',
    groupName: 'Muxway · 国产模型',
    name: '国产模型企业试运行',
    priceCNY: 739,
    monthlyUSDQuota: 1350,
    paygPricePerUSD: 0.50,
    effectivePricePerUSD: 0.55,
    costMultiplier: 0.10,
    supportModels: 'DeepSeek / Kimi / GLM / Qwen 等系统实时上架模型',
    benefits: ['20 席', '30+ 并发', '企业风控', '权益溢价'],
    isEnterprise: true,
    seats: 20,
    concurrency: 30,
    whitelistOnly: true,
    circuitBreakerEnabled: false,
  },
]

// 按产品线分组
export const PLANS_BY_PRODUCT_LINE: Record<ProductLine, SmiralPlan[]> = {
  gpt_plus: SMIRAL_PLANS.filter((p) => p.productLine === 'gpt_plus'),
  gpt_pro: SMIRAL_PLANS.filter((p) => p.productLine === 'gpt_pro'),
  claude_no_fable: SMIRAL_PLANS.filter((p) => p.productLine === 'claude_no_fable'),
  claude_fable: SMIRAL_PLANS.filter((p) => p.productLine === 'claude_fable'),
  domestic: SMIRAL_PLANS.filter((p) => p.productLine === 'domestic'),
}

export const PRODUCT_LINE_DISPLAY: Record<ProductLine, { label: string; tag: string }> = {
  gpt_plus: { label: 'GPT Plus', tag: 'GPT' },
  gpt_pro: { label: 'GPT Pro', tag: 'GPT-Pro' },
  claude_no_fable: { label: 'ClaudeCode', tag: 'Claude' },
  claude_fable: { label: 'ClaudeCode Max', tag: 'Claude-Max' },
  domestic: { label: '国产模型', tag: '国产' },
}
